use_frameworks!

platform :ios, '8.0'

target 'mylib-objc_Example' do
  pod 'mylib-objc', :path => '../'

  target 'mylib-objc_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
